/*
 * Copyright (c) 2026 ttcodebot
 * SPDX-License-Identifier: Apache-2.0
 *
 * 64x8 SRAM (gf180mcu_ocd_ip_sram__sram64x8m8wm1, by Open Circuit Design) brought out on a
 * Tiny Tapeout 1x1 digital tile as a hand-assembled custom GDS (src/tt_um_ttcodebot_sram64x8.gds,
 * generated by scripts/build_tile.py). The 301.3 x 152.2 um macro nearly fills the
 * 346.64 x 160.72 um tile; only the thin connectivity below is added.
 *
 * The macro's CLK/CEN/GWEN/WEN/A/D/Q pins sit on the macro's BOTTOM edge and are channel-routed
 * out to the tile's top-edge I/O. The controls are all ACTIVE-LOW and are exposed directly (no
 * inverters): the write strobe is the active-low ui_in[6]; chip-enable and the per-bit write
 * masks are tied asserted (CEN=0, WEN=0) so every cycle is a full-byte read, or a full-byte write
 * when ui_in[6]=0.
 *
 * Pin map (1 word = 8 bits, 64 words = 6-bit address):
 *   ui_in[5:0] = address A[5:0]
 *   ui_in[6]   = we_n   (0 = write D this cycle, 1 = read)
 *   ui_in[7]   = unused
 *   uio_in[7:0]= D[7:0] write data   (uio used as inputs)
 *   uo_out[7:0]= Q[7:0] read data
 *   clk        = SRAM clock          (ena / rst_n unused — SRAM has no reset)
 */

`default_nettype none

module tt_um_ttcodebot_sram64x8 (
    input  wire [7:0] ui_in,    // address[5:0], we_n, unused
    output wire [7:0] uo_out,   // read data Q[7:0]
    input  wire [7:0] uio_in,   // write data D[7:0]
    output wire [7:0] uio_out,  // unused (driven 0)
    output wire [7:0] uio_oe,   // all inputs (driven 0)
    input  wire       ena,      // unused
    input  wire       clk,      // SRAM clock
    input  wire       rst_n     // unused (SRAM has no reset)
);

  // The bidirectional pins are used purely as inputs (write data); tie outputs/enables low.
  assign uio_out = 8'b0;
  assign uio_oe  = 8'b0;

  // SRAM controls are ACTIVE-LOW and connected directly in the GDS (no inverters):
  //   CEN  = 1'b0          chip always enabled
  //   GWEN = ui_in[6]      active-low write enable (0 = write this cycle)
  //   WEN  = 8'b0          all 8 bit-write masks asserted -> full-byte write when GWEN=0
  gf180mcu_ocd_ip_sram__sram64x8m8wm1 sram (
      .CLK  (clk),
      .CEN  (1'b0),
      .GWEN (ui_in[6]),
      .WEN  (8'b0),
      .A    (ui_in[5:0]),
      .D    (uio_in),       // write data
      .Q    (uo_out)        // read data
  );

  // Silence unused-signal lint (ui_in[7], ena, rst_n are unused).
  wire _unused = &{ena, rst_n, ui_in[7], 1'b0};

endmodule

`default_nettype wire
